logging:
  level: debug

server:
  port: 9090
  address:

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miguo_matrix?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Hechenghan1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    port: 32768
    password:
    database: 0
file:
  path:
