logging:
  level: error

server:
  port: 9090
  address:
#  ssl:
#    key-store: classpath:ad.hocassian.cn.jks
#    key-store-password: gKFtOquzlR
#    keyStoreType: JKS

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miguo-matrix?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 5f5bb7c8fd9757fe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
file:
  path:
