logging:
  level: debug

server:
  port: 9090
  address:

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miguo_matrix?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: Hechenghan1234
#    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
file:
  path: F:/test/
