logging:
  level: error

server:
  port: 9090
  address:
  ssl:
    key-store: classpath:migotimes.com.jks
    key-store-password: gKFtOquzlR
    keyStoreType: JKS

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miguo_matrix?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: b66a33eca6314e6a
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
file:
  path:
