logging:
  level: error

server:
  port: 443
  address:
  ssl:
    key-store: classpath:xxx.com.jks
    key-store-password: 
    keyStoreType: JKS

spring:
  rabbitmq:
    port: 5672
    username: xxx
    password: xxx
    host: localhost
    virtual-host: /upload
    durable: true
  datasource:
    url: jdbc:mysql://localhost:3306/miguo_matrix?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xxx
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
file:
  path: /home/ubuntu/migo_back_end/file/
