info:
  app:
    name: miguo-matrix-back-end
    version: 1.0.1

output:
  ansi:
    enabled: ALWAYS # 输出带颜色的日志信息

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port:
  address:
  servlet:
    context-path:
    session:
      timeout: 30m
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  mvc:
    date-format: yyyy-MM-dd
    throw-exception-if-no-handler-found: true # 找不到处理器直接抛出异常
  resources:
    add-mappings: false # 不要为我们工程中的资源文件建立映射
  jackson:
    date-format: java.text.SimpleDateFormat
    time-zone: GMT+8
    serialization.indent_output: true
  session:
    store-type: redis
    #    timeout:
    redis:
      flush-mode: on_save
  datasource:
    name: MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:
    sql-script-encoding: utf-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    open-in-view: true
  redis:
    host:
    port:
    password:
    database:
    ssl: false
    timeout: 6000ms
    jedis:
      pool:
        max-active: 200   # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 1       # 连接池中的最小空闲连接

#  security:
#    basic:
#      enabled: true
#      path: /swagger-ui.html
#    user:
#      name: user
#      password: 123456

management:
  endpoints:
    web:
      base-path: /manage
  server:
    servlet:
      context-path: /manage

snowflake:
  workerId: 0
  datacenterId: 0

file:
  path:
