logging:
  level: error

server:
  port: 9090
  address:
#  ssl:
#    key-store: classpath:ad.hocassian.cn.jks
#    key-store-password: gKFtOquzlR
#    keyStoreType: JKS

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/miguo-matrix?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 5f5bb7c8fd9757fe
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  redis:
    host: 127.0.0.1
    port: 32768
    password:
    database: 0
file:
  path:
